export const eventName = {
    REQUEST_EDG_CALLED: 'REQUEST_EDG_CALLED',
    REQUEST_EDG_FAILED: 'REQUEST_EDG_FAILED',
    REQUEST_EDG_SUCCEED: 'REQUEST_EDG_SUCCEED',

    GET_BALANCE_CALLED: 'GET_BALANCE_CALLED',
    GET_BALANCE_SUCCEED: 'GET_BALANCE_SUCCEED',
    GET_BALANCE_FAILED: 'GET_BALANCE_FAILED',
}